version: '3.2'


volumes:

  node1-data: null
  node2-data: null


services:

  node1:
    build:
      context: ./
      dockerfile: Dockerfile-ethereum
    command: '--networkid=1377'
            # --mine --minerthreads=1 --etherbase=0x0000000000000000000000000000000000000001'
    restart: on-failure
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - node1-data:/root/.ethereum


  node2:
    build:
      context: ./
      dockerfile: Dockerfile-ethereum
    command: '--networkid=1377'
    restart: on-failure
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - node2-data:/root/.ethereum


